### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by MisterSingh** [Strategizer/app#12]
Requirements: 
Create using [AppBar of material UI](https://material-ui.com/components/app-bar/#app-bar).
-  Left Side: GitHub repository link
-  Right Side: Maintainers

**Comment by alisherk** [comment]
I would like to take this one.

**Comment by quelingeeson** [comment]
Hi @alisherk ,

You can work on this. Let us know if you have any doubts.

**Comment by alisherk** [comment]
here it is 
#16
